export const feminineProducts = [
    {
        id: "x6uKr_NkeP",
        name: 'Casual Top',
        desc: 'Casual pink top',
        price: 20,
        url: "https://5.imimg.com/data5/WS/DS/MY-28162106/ladies-top-500x500.jpg",
        addedToCart: false,
        category: "Female",
    },
    {
        id: "tJ6HI4hMrI",
        name: 'Queen Top',
        desc: 'Wine Queen top for women',
        price: 35,
        url: "https://m.media-amazon.com/images/I/61G4kcTPPiL._UL1400_.jpg",
        addedToCart: false,
        category: "Female",
    },
    {
        id: "Q7nIT4jdBh",
        name: 'Bell Bottom Pants',
        desc: 'Black leisure trousers for women',
        price: 50,
        url: "https://image.made-in-china.com/202f0j00BHCfdEwGEMbl/Bell-Bottom-Pants-for-Ladies-Black-Color-Leisure-Trouser.jpg",
        addedToCart: false,
        category: "Female",
    },
    {
        id: "DyDlMp_7hi",
        name: 'Blue Jeans',
        desc: 'Slim fit regular blue jeans for women',
        price: 25,
        url: "https://outfitideashq.com/wp-content/uploads/2014/07/women-wearing-super-skinny-jeans.jpeg",
        addedToCart: false,
        category: "Female",
    },
    {
        id: "wMERbw6yaS",
        name: 'Stylish Skirt',
        desc: 'Red fashion skirt for women',
        price: 25,
        url: "https://4.imimg.com/data4/CV/OX/MY-2428689/ladies-skirt-500x500.jpg",
        addedToCart: false,
        category: "Female",
    },
    {
        id: "bF1RjKg9Ql",
        name: 'Pink Casual Shoes',
        desc: 'Summer pink casual shoes for women',
        price: 50,
        url: "https://i.pinimg.com/originals/ab/5a/6f/ab5a6f9869d2938d8abe5d39eab3ebea.jpg",
        addedToCart: false,
        category: "Female",
    },
    // {
    //     id: 7,
    //     name: 'Heel Shoes',
    //     desc: 'Blue leather heel shoes for women',
    //     price: 100,
    //     url: "https://www.buyon.pk/image/cache/data/members/choicesonlinestore/product-images/blue-leather-heel-pumps-600x600.jpg",
    //     addedToCart: false,
    // },
    // {
    //     id: 8,
    //     name: 'Classic Hand Bag',
    //     desc: 'Ladies Classic light brown handbag',
    //     price: 60,
    //     url: "https://5.imimg.com/data5/NI/HL/SC/SELLER-39862343/classy-ladies-shoulder-bag-1000x1000.jpg",
    //     addedToCart: false,
    // },
]